[package]
name = "tls"
version = "0.1.0"
edition = "2021"

# Mark the `check-certs` binary as the default.
default-run = "check-certs"

[[bin]]
name = "check-certs"
path = "src/bin/check-certs.rs"

[[bin]]
name = "gen-certs"
path = "src/bin/gen-certs.rs"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"

[dependencies]
# TLS dependencies.
rustls = "0.23.19"
tokio-rustls = "0.26.0"
rustls-pemfile = "2.2.0"

# Tokio dependencies.
tokio = { version = "1.42.0", features = ["full"] }

# Tokio tracing dependencies.
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

# Error handling.
miette = "7.4.0"

# Terminal color output.
crossterm = "0.28.1"

# Strum dependencies.
strum = "0.26.3"
strum_macros = "0.26.4"

# R3BL awesomeness.
futures-util = "0.3.31"                                            # Async streams.
r3bl_core = { git = "https://github.com/r3bl-org/r3bl-open-core" } # Use latest version for `create_global_singleton!`

# Use latest version for: `create_temp_dir()`, `gen_input_stream_with_delay()`
r3bl_test_fixtures = { git = "https://github.com/r3bl-org/r3bl-open-core" } # Stable, but not released
# r3bl_test_fixtures = { path = "/home/nazmul/github/r3bl-open-core/test_fixtures" } # Unstable, active development

# Dynamically name variables in declarative macros.
paste = "1.0.15"

# HTTP client library.
reqwest = { version = "0.12.9", features = ["json"] }
serde_json = "1.0.133"
