[package]
name = "tls"
version = "0.1.0"
edition = "2021"

# Mark the `check-certs` binary as the default.
default-run = "check-certs"

[[bin]]
name = "check-certs"
path = "src/bin/check-certs.rs"

[[bin]]
name = "gen-certs"
path = "src/bin/gen-certs.rs"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"

[dependencies]
# TLS dependencies.
rustls = "0.23.18"
tokio-rustls = "0.26.0"
rustls-pemfile = "2.2.0"

# Tokio dependencies.
tokio = { version = "1.41.1", features = ["full"] }

# Error handling.
miette = "7.2.0"

# Terminal color output.
crossterm = "0.28.1"

# R3BL awesomeness.
r3bl_core = "0.10.0"
r3bl_test_fixtures = "0.1.0" # Used to simulate user input into the terminal when running client and server.
futures-util = "0.3.31"      # Async streams.
