[package]
name = "rcat"
version = "0.1.0"
edition = "2021"
about = "A simple Rust netcat clone that uses only TCP"
author = ["Nazmul Idris <idris@developerlife.com>"]

[dependencies]
clap = { version = "4.4.13", features = ["derive"] }
crossterm = { version = "0.27.0" }
