[package]
name = "tcp-api-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Async CLI UI.
r3bl_terminal_async = { version = "0.5.3" }

r3bl_tui = { version = "0.5.5" }
r3bl_rs_utils_core = { version = "0.9.13" }
crossterm = "0.27.0"

# Command line argument parsing.
clap = { version = "4.5.4", features = ["derive"] }
color-print = "0.3.6"

# Serde for serialization and deserialization support.
serde = { version = "1.0.198", features = ["derive"] }
serde_json = { version = "1.0.116" }

# Convert Rust structs to and from binary representation.
bincode = { version = "1.3.3" }

# Enum to string generation.
strum = "0.26"
strum_macros = "0.26"

# Key Value store that can be used to store JSON or bincode encoded values. `kv` is built
# on top of `sled` which currently does not support access across multiple processes.
kv = { version = "0.24.0", features = ["json-value", "bincode-value"] }

# Error handling.
thiserror = "1.0.59"
miette = { version = "7.2.0", features = ["fancy"] }
pretty_assertions = "1.4.0"

# Random numbers.
rand = "0.8.5"

# Tokio / Tracing / Logging / Testing / Utils.
# https://tokio.rs/tokio/topics/tracing
# https://tokio.rs/tokio/topics/tracing-next-steps
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tokio = { version = "1.37.0", features = ["full", "tracing"] }
tokio-test = "0.4.4"                                                   # For mock `TcpStream` (`Builder`)

[dev-dependencies]
tempfile = "3.2.0"
serial_test = "3.1.0"
# Allows you to export data to Jaeger
