[package]
name = "tcp-api-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Terminal user interface.
r3bl_tui = { version = "0.5.2" }
r3bl_rs_utils_core = { version = "0.9.12" }
crossterm = "0.27.0"
ctrlc = "3.4.4"

# Prompt user for input.
r3bl_terminal_async = { path = "/home/nazmul/github/r3bl_terminal_async" }
futures-channel = "0.3"
futures-util = { version = "0.3", features = ["io"] }

# Command line argument parsing.
clap = { version = "4.4.13", features = ["derive"] }
color-print = "0.3.5"

# Random numbers.
rand = { version = "0.8.5" }

# Serde for serialization and deserialization support.
serde = { version = "1.0.197", features = ["derive"] }
serde_json = { version = "1.0.115" }

# Convert Rust structs to and from binary representation.
bincode = { version = "1.3.3" }

# Key Value store that can be used to store JSON or bincode encoded values. `kv` is built
# on top of `sled` which currently does not support access across multiple processes.
kv = { version = "0.24.0", features = ["json-value", "bincode-value"] }

# Error handling.
thiserror = "1.0.58"
miette = { version = "7.2.0", features = ["fancy"] }
pretty_assertions = "1.4.0"

# Tokio / Tracing / Logging.
# https://tokio.rs/tokio/topics/tracing
# https://tokio.rs/tokio/topics/tracing-next-steps
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = "0.3.18"
tokio = { version = "1.37.0", features = ["full", "tracing"] }
