[package]
name = "syn-hi"
version = "0.1.0"
edition = "2021"

[dependencies]

# Extract frontmatter from MD files.
extract-frontmatter = "4.1.1"
serde_json = "1.0.87"
yaml-rust = "0.4.5"

# MD to AST.
pulldown-cmark = "0.9.2"