[package]
name = "memory_locality"
version = "0.1.0"
edition = "2024"

[dependencies]
r3bl_tui = { git = "https://github.com/r3bl-org/r3bl-open-core", branch = "main", package = "r3bl_tui" }

[dev-dependencies]
serial_test = "3.0"
