[package]
name = "memory_locality"
version = "0.1.0"
edition = "2024"

[dependencies]
r3bl_tui = "0.7.1"
smallstr = "0.3.0"
smallvec = "1.15.0"
tikv-jemallocator = "0.6.0"

[dev-dependencies]
serial_test = "3.0"
