[package]
name = "tokio-uring"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-uring = "0.4.0"
miette = { version = "7.2.0", features = ["fancy"] }
crossterm = { version = "0.27.0", features = ["event-stream"] }
